#!/usr/bin/env bash
# A bash script that will display information about subdomains

domain_information() {
    local result
    result=$(dig "$2"."$1" +short)
    
    if [ -z "$result" ]; then
        echo "The subdomain $2 does not exist."
    else
        local record_type
        record_type=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print $4}')
        echo "The subdomain $2 is a $record_type record and points to $result"
    fi
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

